// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, user_id, tenant_id, name, secret_hash) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, tenant_id, name, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID         string      `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Name       string      `json:"name"`
	SecretHash string      `json:"secret_hash"`
}

type CreateAPIKeyRow struct {
	ID        string             `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Name,
		arg.SecretHash,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (jti, user_id, expires_at) VALUES ($1, $2, $3)
RETURNING jti, user_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	Jti       pgtype.UUID        `json:"jti"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, tenant_id, name, secret_hash, created_at, revoked_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Name,
		&i.SecretHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, user_id, expires_at, revoked_at, created_at FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, created_at, revoked_at FROM api_keys WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, tenantID pgtype.UUID) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE jti = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	return err
}
