// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (tenant_id, language, source, stdin)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, language, status, created_at
`

type CreateExecutionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Language string      `json:"language"`
	Source   string      `json:"source"`
	Stdin    string      `json:"stdin"`
}

type CreateExecutionRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Language  string             `json:"language"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (CreateExecutionRow, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.TenantID,
		arg.Language,
		arg.Source,
		arg.Stdin,
	)
	var i CreateExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Language,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, tenant_id, language, status, source, stdin, stdout, stderr, exit_code, created_at, updated_at
FROM executions WHERE id = $1 AND tenant_id = $2
`

type GetExecutionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.ID, arg.TenantID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Language,
		&i.Status,
		&i.Source,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, language, status, created_at, updated_at
FROM executions WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListExecutionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListExecutionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Language  string             `json:"language"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listExecutions, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionsRow
	for rows.Next() {
		var i ListExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
