// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (tenant_id, language, source, stdin, timeout_s, webhook_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, language, status, created_at
`

type CreateExecutionParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Language   string      `json:"language"`
	Source     string      `json:"source"`
	Stdin      string      `json:"stdin"`
	TimeoutS   int32       `json:"timeout_s"`
	WebhookUrl pgtype.Text `json:"webhook_url"`
}

type CreateExecutionRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Language  string             `json:"language"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (CreateExecutionRow, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.TenantID,
		arg.Language,
		arg.Source,
		arg.Stdin,
		arg.TimeoutS,
		arg.WebhookUrl,
	)
	var i CreateExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Language,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const finishExecution = `-- name: FinishExecution :exec
UPDATE executions
SET status = $2, stdout = $3, stderr = $4, exit_code = $5, updated_at = now()
WHERE id = $1 AND status = 'running'
`

type FinishExecutionParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Stdout   string      `json:"stdout"`
	Stderr   string      `json:"stderr"`
	ExitCode pgtype.Int4 `json:"exit_code"`
}

// Writes a result for a running execution. status is one of
// succeeded/failed/timeout (validated by the status CHECK constraint).
func (q *Queries) FinishExecution(ctx context.Context, arg FinishExecutionParams) error {
	_, err := q.db.Exec(ctx, finishExecution,
		arg.ID,
		arg.Status,
		arg.Stdout,
		arg.Stderr,
		arg.ExitCode,
	)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, tenant_id, language, status, source, stdin, stdout, stderr, exit_code, created_at, updated_at
FROM executions WHERE id = $1 AND tenant_id = $2
`

type GetExecutionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetExecutionRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Language  string             `json:"language"`
	Status    string             `json:"status"`
	Source    string             `json:"source"`
	Stdin     string             `json:"stdin"`
	Stdout    string             `json:"stdout"`
	Stderr    string             `json:"stderr"`
	ExitCode  pgtype.Int4        `json:"exit_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (GetExecutionRow, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.ID, arg.TenantID)
	var i GetExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Language,
		&i.Status,
		&i.Source,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.ExitCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, language, status, created_at, updated_at
FROM executions WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListExecutionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListExecutionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Language  string             `json:"language"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listExecutions, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionsRow
	for rows.Next() {
		var i ListExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExecutionRunning = `-- name: MarkExecutionRunning :execrows
UPDATE executions
SET status = 'running', updated_at = now()
WHERE id = $1 AND status = 'queued'
`

// Claims a queued execution for the dispatcher. Only the claim that
// transitions queued->running runs the code; duplicate JetStream deliveries
// (at-least-once) see 0 rows and are acked and skipped.
func (q *Queries) MarkExecutionRunning(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markExecutionRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapStaleExecutions = `-- name: ReapStaleExecutions :execrows
UPDATE executions
SET status = 'failed', stderr = $1, updated_at = now()
WHERE status = 'running' AND updated_at < now() - make_interval(secs => $2::int)
`

type ReapStaleExecutionsParams struct {
	Stderr    string `json:"stderr"`
	StaleSecs int32  `json:"stale_secs"`
}

// Fails executions stuck "running" because their dispatcher died between
// claim and finish. Guarded by status + staleness, so multiple replicas and
// late JetStream redeliveries are harmless.
func (q *Queries) ReapStaleExecutions(ctx context.Context, arg ReapStaleExecutionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reapStaleExecutions, arg.Stderr, arg.StaleSecs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setExecutionFailed = `-- name: SetExecutionFailed :exec
UPDATE executions
SET status = 'failed', stderr = $2, updated_at = now()
WHERE id = $1 AND status = 'queued'
`

type SetExecutionFailedParams struct {
	ID     pgtype.UUID `json:"id"`
	Stderr string      `json:"stderr"`
}

// Marks a queued execution failed (e.g. the submit queue was unreachable).
func (q *Queries) SetExecutionFailed(ctx context.Context, arg SetExecutionFailedParams) error {
	_, err := q.db.Exec(ctx, setExecutionFailed, arg.ID, arg.Stderr)
	return err
}
