// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string             `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Name       string             `json:"name"`
	SecretHash string             `json:"secret_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Execution struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Language   string             `json:"language"`
	Status     string             `json:"status"`
	Source     string             `json:"source"`
	Stdin      string             `json:"stdin"`
	Stdout     string             `json:"stdout"`
	Stderr     string             `json:"stderr"`
	ExitCode   pgtype.Int4        `json:"exit_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TimeoutS   int32              `json:"timeout_s"`
	WebhookUrl pgtype.Text        `json:"webhook_url"`
}

type Membership struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Namespace string             `json:"namespace"`
	Tier      string             `json:"tier"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
