// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (user_id, tenant_id, role) VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role
`

type AddMembershipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Role     string      `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.UserID, arg.TenantID, arg.Role)
	return err
}

const checkMembership = `-- name: CheckMembership :one
SELECT role FROM memberships WHERE user_id = $1 AND tenant_id = $2
`

type CheckMembershipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CheckMembership(ctx context.Context, arg CheckMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, checkMembership, arg.UserID, arg.TenantID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, namespace, tier) VALUES ($1, $2, $3)
RETURNING id, slug, namespace, tier, created_at
`

type CreateTenantParams struct {
	Slug      string `json:"slug"`
	Namespace string `json:"namespace"`
	Tier      string `json:"tier"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.Namespace, arg.Tier)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Namespace,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}
