// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash) VALUES ($1, $2, $3)
RETURNING id, email, username, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantMemberships = `-- name: ListTenantMemberships :many
SELECT t.id, t.slug, t.namespace, t.tier, m.role
FROM memberships m JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1
`

type ListTenantMembershipsRow struct {
	ID        pgtype.UUID `json:"id"`
	Slug      string      `json:"slug"`
	Namespace string      `json:"namespace"`
	Tier      string      `json:"tier"`
	Role      string      `json:"role"`
}

func (q *Queries) ListTenantMemberships(ctx context.Context, userID pgtype.UUID) ([]ListTenantMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTenantMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantMembershipsRow
	for rows.Next() {
		var i ListTenantMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Namespace,
			&i.Tier,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
